name: project_environment
channels:
- defaults
- pytorch
dependencies:
- python=3.6.8
- pytorch=1.5.0
- torchvision=0.6.0
- pip:
  - azureml-defaults==0.1.0.*
  - --index-url https://azuremlsdktestpypi.azureedge.net/dev/aml/office/134157926D8F 
  - --extra-index-url https://pypi.org/simple
  - pandas==0.25.3
  - numpy==1.18.1
  - pyarrow==0.16.0
  - scikit-learn==0.22.2
  - nltk==3.4
  - matplotlib==3.1.0